package main

func main() {
	// TryMath()
	// TryForIsGosWhile()
	// TryVariable()
	// TryFor()
	// TryIf()
	// TryFunction()
	// TryNumericConstants()
	// TryTypeInference()
	// TryTypeConversion()
	// TryForever()
	// TryTimeFormat()
	// TryRandIntn()
	// TryZeroValues()
	// TryBasicTypes()
	// TryConstants()
	// TryIfWithShortStatement()
	// TryIfAndElse()
	// TryExerciseLoopAndFunctions()
	// TrySwitchCase()
	// TrySwitchEvaluationOrder()
	// TrySwitchWithNoCondition()
	// TryDefer()
	// TryStackingDefer()
	// TryPointer()
	// TryStruct()
	// TryStructFields()
	// TryStructPointer()
	// TryStructLiterals()
	// TryArray()
	// TrySlice()
	// TrySlicePointers()
	// TrySliceLiterals()
	// TrySliceBounds()
	// TrySliceLenCap()
	// TryNilSlice()
	// TryMakingSlices()
	// TrySlicesOfSlices()
	// TryAppend()
	// TryRange()
	// TryRangeContinued()
	TryExerciseSlice()
}
